version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: consent-demo-postgres
    environment:
      POSTGRES_DB: identityserver
      POSTGRES_USER: identityserver
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - consent-demo-network

  duende-identity-server:
    image: duendesoftware/identityserver:7.0
    container_name: consent-demo-duende
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=identityserver;Username=identityserver;Password=password"
    ports:
      - "9980:80"
    depends_on:
      - postgres
    networks:
      - consent-demo-network

volumes:
  postgres_data:

networks:
  consent-demo-network:
    driver: bridge
