version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: consent-demo-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - consent-demo-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: consent-demo-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9980:8080"
    depends_on:
      - postgres
    command: start-dev
    networks:
      - consent-demo-network

volumes:
  postgres_data:

networks:
  consent-demo-network:
    driver: bridge
